export const ADD_CART_ITEM="ADD_CART_ITEM";
export const REMOVE_CART_ITEM="REMOVE_CART_ITEM"
export const FAIL_CART="FAIL_CART"
export const SAVE_SHIPPING_ADRESS="SAVE_SHIPPING_ADRESS"
export const SAVE_PAYMENT_METHOD="SAVE_PAYMENT_METHOD"