export const ADD_CART_ITEM="ADD_CART_ITEM";
export const REMOVE_CART_ITEM="REMOVE_CART_ITEM"
export const FAIL_CART="FAIL_CART"
export const SAVE_SHIPPING_ADRESS="SAVE_SHIPPING_ADRESS"
export const SAVE_PAYMENT_METHOD="SAVE_PAYMENT_METHOD"
export const RESET_CART_ITEMS="RESET_CART_ITEMS"
export const SAVE_TOTAL_PRICE ="SAVE_TOTAL_PRICE "
export const SAVE_TOTAL_ITEMS="SAVE_TOTAL_ITEMS"