export const FAILPRODUCTLIST="PRODUCT_LIST_FAIL"
export const PENDINGPRODUCTLIST="PRODUCT_LIST_PENDING"
export const SUCCESSPRODUCTLIST="PRODUCT_LIST_SUCCESS"



//Product Item
export const PRODUCT_PENDING="PRODUCT_PENDING"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const PRODUCT_FAIL="PRODUCT_FAIL"