export const FAILPRODUCTLIST="PRODUCT_LIST_FAIL"
export const PENDINGPRODUCTLIST="PRODUCT_LIST_PENDING"
export const SUCCESSPRODUCTLIST="PRODUCT_LIST_SUCCESS"
export const GET_TOP_RATED_PRODUCTS="GET_TOP_RATED_PRODUCTS"


//Product Item
export const PRODUCT_PENDING="PRODUCT_PENDING"
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS"
export const PRODUCT_FAIL="PRODUCT_FAIL"
export const UPDATE_PRODUCT_REVIEW="UPDATE_PRODUCT_REVIEW"