export const USERDETAILS_REQUEST="USERDETAILS_REQUEST";
export const USERDETAILS_SUCCESS="USERDETAILS_SUCCESS";
export const USERDETAILS_FAIL="USERDETAILS_FAIL"
export const CLEAR_USER_DETAILS="CLEAR_USER_DETAILS"